import type { InsertProduct } from "@shared/schema";

export const seedProducts: InsertProduct[] = [
  // ── SILICONE FLUIDS (PDMS) ───────────────────────────────────────────────
  {
    name: "Resifluid-350 Silicone Fluid",
    description: "RESIFLUID-350 is a colorless polydimethylsiloxane (PDMS) fluid from Resil Chemicals with approximately 370 cst viscosity. It offers excellent thermal stability, low surface tension, high compressibility, and good dielectric properties.",
    applications: "Used as a release agent, antifoam, hydraulic fluid, surface-active material, lubricant, and as an additive in polishes and chemical specialties.",
    targetIndustries: ["Rubber & Latex", "Personal Care & Cosmetics", "Pharmaceuticals", "Paper & Pulp", "Food Processing", "Medical Devices"],
    keywords: ["silicone fluid", "resifluid", "pdms", "polydimethylsiloxane", "release agent", "antifoam", "lubricant", "silicone oil", "350 cst", "resil"],
    source: "pdf",
    pdfName: "TDS-RESILFLUID-350.pdf",
  },
  {
    name: "DMC Silicone Fluids (Dimethicone)",
    description: "DMC grade silicone fluids are clear, colorless polydimethylsiloxane fluids from Resil Chemicals available in viscosities from 0.65 to 60,000 cst. They are non-greasy, form protective breathable films, and have excellent water repellency.",
    applications: "Used for siliconization of glass, metals, plastics, and rubber. Key applications include pharmaceutical and cosmetic formulations (skin care, sun care, oral care), medical device lubrication (syringes, needles), and industrial lubrication.",
    targetIndustries: ["Personal Care & Cosmetics", "Pharmaceuticals", "Medical Devices", "Rubber & Latex", "PVC & Plastics"],
    keywords: ["dimethicone", "dmc", "silicone fluid", "pdms", "polydimethylsiloxane", "cosmetic grade", "pharmaceutical grade", "siliconization", "lubricant", "resil"],
    source: "pdf",
    pdfName: "DMC_FLUIDS_TDS.pdf",
  },
  {
    name: "Silicone Oil (PDMS)",
    description: "Polydimethylsiloxane (PDMS) silicone oil available in low (0.65–10 cSt), medium (20–1,000 cSt) and high (5,000–65,000 cSt) viscosity grades. Clear, colorless, odorless and non-toxic with excellent thermal stability and dielectric properties.",
    applications: "Glass and metal siliconization, protective films, dielectric coolants, medical device lubrication, textile finishing, and anti-foam agent across multiple industries.",
    targetIndustries: ["Medical Devices", "Rubber & Latex", "Personal Care & Cosmetics", "Pharmaceuticals", "Paper & Pulp", "Food Processing"],
    keywords: ["silicone oil", "pdms", "polydimethylsiloxane", "dimethicone", "dielectric", "release agent", "lubricant", "textile", "siliconization", "viscosity"],
    source: "text",
    pdfName: null,
  },

  // ── AGROCHEMICAL ADJUVANTS ────────────────────────────────────────────────
  {
    name: "Resilwet 103 (Trisiloxane Spray Adjuvant)",
    description: "RESILWET 103 is a polyether modified trisiloxane adjuvant (3-(Polyoxyethylene)propylheptamethyltrisiloxane) from Resil Chemicals. A highly effective non-ionic surfactant that reduces surface tension below 25 mN/m.",
    applications: "Spray adjuvant in agricultural applications for improved wetting, spreading, and stomatal penetration of herbicides, pesticides, fungicides, foliar nutrients, plant growth regulators, and biological formulations.",
    targetIndustries: ["Agriculture & Agrochemicals"],
    keywords: ["spray adjuvant", "resilwet", "trisiloxane", "surfactant", "wetter", "spreader", "agricultural adjuvant", "agrochemical", "resil", "silicone surfactant", "super spreader"],
    source: "pdf",
    pdfName: "RESILWET_103_SDS.pdf",
  },
  {
    name: "Super-Spreader Adjuvants (OMRI Listed)",
    description: "Range of trisiloxane ethoxylate-based super-spreader adjuvants including standard, high-performance, rain-fast, and economical grades. OMRI-listed options available for organic use. Reduce spray surface tension to enable stomatal flooding.",
    applications: "Tank-mix adjuvants for herbicides, pesticides, fungicides, foliar nutrients, and biologicals. Suitable for turf, horticulture, broadacre cropping, and certified organic programs.",
    targetIndustries: ["Agriculture & Agrochemicals"],
    keywords: ["super spreader", "trisiloxane", "omri", "organic adjuvant", "rain fast", "stomatal", "tank mix", "crop protection", "spray", "silicone adjuvant"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Powder-Based Super-Spreader Adjuvants",
    description: "Organo-modified trisiloxane-based adjuvants in powder form, including dispersible powder and standard powder grades. Offer easy handling, extended shelf life, and compatibility with powder formulations.",
    applications: "Used in wettable powder (WP) and water-dispersible granule (WDG) formulations for crop protection products including herbicides, fungicides, and insecticides.",
    targetIndustries: ["Agriculture & Agrochemicals"],
    keywords: ["powder adjuvant", "dispersible powder", "wdg", "wp", "trisiloxane powder", "crop protection", "herbicide", "fungicide", "wettable powder", "granule"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Biodegradable Super-Spreader (OECD 301-B)",
    description: "Biodegradable organo-modified trisiloxane adjuvant certified to OECD 301-B biodegradation standard and OMRI listed for organic agriculture. Meets stringent environmental compliance requirements.",
    applications: "Environmentally-compliant spray adjuvant for use in sensitive ecosystems, near water bodies, or in markets requiring biodegradable formulation ingredients.",
    targetIndustries: ["Agriculture & Agrochemicals"],
    keywords: ["biodegradable adjuvant", "oecd 301b", "eco adjuvant", "trisiloxane", "omri organic", "environmentally friendly", "sustainable agriculture", "spray additive"],
    source: "text",
    pdfName: null,
  },

  // ── AGROCHEMICAL ANTIFOAMS ────────────────────────────────────────────────
  {
    name: "Silicone Emulsion Antifoam (Agrochemical Grade)",
    description: "High-performance and multi-formulation grade silicone emulsion antifoams designed for use in agrochemical manufacturing. Effective in high-shear mixing with rapid foam knockdown.",
    applications: "Defoaming agent in the manufacture and application of herbicides, insecticides, fungicides, and foliar nutrient formulations.",
    targetIndustries: ["Agriculture & Agrochemicals", "Water Treatment"],
    keywords: ["antifoam", "defoamer", "silicone emulsion", "agro defoamer", "herbicide manufacturing", "foam control", "emulsion antifoam", "formulation additive"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Silicone Glycol Antifoams (Liquid & Powder)",
    description: "Range of silicone glycol antifoams available as liquid (high-performance and stable grades) and powder formats, plus a 100% self-dispersing version. Suitable for aqueous and non-aqueous systems.",
    applications: "Foam control in agrochemical formulations, rubber latex processing, and other industrial processes requiring compatibility with glycol-based systems.",
    targetIndustries: ["Agriculture & Agrochemicals", "Rubber & Latex", "Paper & Pulp"],
    keywords: ["silicone glycol", "antifoam powder", "self dispersing antifoam", "foam control", "latex antifoam", "paper antifoam", "defoamer", "silicone glycol antifoam"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Dispersing Agents for Agrochemicals",
    description: "Sodium salt of alkylnaphthalene sulphonate condensate (liquid and dispersion grades). Anionic dispersing agents for stable suspension concentrate formulations.",
    applications: "Used in suspension concentrates (SC), wettable powders (WP), and water-dispersible granules (WDG) to ensure uniform ingredient distribution and suspension stability.",
    targetIndustries: ["Agriculture & Agrochemicals"],
    keywords: ["dispersing agent", "alkylnaphthalene", "sodium sulphonate", "suspension concentrate", "sc formulation", "wdg", "wettable powder", "dispersant", "agro formulation"],
    source: "text",
    pdfName: null,
  },

  // ── RUBBER / MOULD RELEASE ────────────────────────────────────────────────
  {
    name: "Silicone Mould Release Agent (Tire & Rubber)",
    description: "Non-ionic PDMS emulsion mould release agent available in 35% and 60% active concentrations. Alkylaryl-modified polysiloxane paintable grade also available for die-casting applications.",
    applications: "Tire molding, rubber goods manufacturing, aluminum and zinc die-casting. The paintable grade leaves no silicone residue and does not carbonize at extreme temperatures.",
    targetIndustries: ["Rubber & Latex", "Footwear", "Medical Devices"],
    keywords: ["mould release", "tire release agent", "pdms emulsion", "rubber release", "die casting", "paintable release", "silicone release", "polysiloxane", "molding"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Silica-Filled Process Defoamer (Rubber Latex)",
    description: "100% active silica-filled polydimethylsiloxane process defoamer for rubber latex processing. Provides effective foam knockdown and long-lasting suppression in latex systems.",
    applications: "Foam control during rubber latex compounding, dipping, and processing operations where concentrated defoaming action is required.",
    targetIndustries: ["Rubber & Latex"],
    keywords: ["latex defoamer", "rubber latex", "silica filled defoamer", "pdms defoamer", "100% active", "process defoamer", "foam control", "latex compounding"],
    source: "text",
    pdfName: null,
  },

  // ── WATER REPELLENTS / CONSTRUCTION ──────────────────────────────────────
  {
    name: "Aquaphobe WR 22 (Silane-Siloxane Emulsion)",
    description: "AQUAPHOBE WR 22 is a water-thinnable, solvent-free silane-siloxane emulsion from Resil Chemicals with excellent penetration properties providing superior water repellency for mineral substrates.",
    applications: "Hydrophobic impregnation of bricks, sandstone, fiber cement boards, aerated concrete, and mineral plasters. Water-repellent primer for emulsion paints.",
    targetIndustries: ["Construction Chemicals", "Paints & Coatings"],
    keywords: ["water repellent", "aquaphobe", "silane siloxane", "hydrophobic", "impregnation", "waterproofing", "construction", "primer", "resil", "wr 22"],
    source: "pdf",
    pdfName: "AQUAPHOBE_WR_22_TDS.pdf",
  },
  {
    name: "Potassium Methyl Siliconate (Water Repellent)",
    description: "Aqueous potassium methyl siliconate solution, a water-based penetrating water repellent that reacts with mineral substrates to form a permanently bonded hydrophobic layer.",
    applications: "Water repellent treatment for bricks, natural stone, and terracotta. Used in construction and restoration projects requiring deep penetration and long-lasting protection.",
    targetIndustries: ["Construction Chemicals"],
    keywords: ["potassium methyl siliconate", "water repellent", "masonry sealer", "brick sealer", "stone protection", "siliconate", "hydrophobic", "construction waterproofing"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Octyltriethoxysilane (Concrete Sealer)",
    description: "100% active octyltriethoxysilane, a monomeric alkylsilane that penetrates deeply into concrete to provide hydrophobic protection against water and chloride ion ingress.",
    applications: "Hydrophobic sealer for concrete structures, bridges, and parking structures. Provides freeze-thaw protection and chloride ion resistance for reinforced concrete.",
    targetIndustries: ["Construction Chemicals"],
    keywords: ["octyltriethoxysilane", "concrete sealer", "alkylsilane", "chloride protection", "bridge sealer", "freeze thaw", "concrete waterproofing", "hydrophobic silane"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Silane/Siloxane Micro-Emulsions (Low VOC)",
    description: "Water-borne penetrating silane/siloxane micro-emulsion sealers with low VOC content. Provide deep penetration and durable hydrophobic protection for porous mineral substrates.",
    applications: "Sealing of concrete bridges, parking structures, natural stone, and masonry. Offers freeze-thaw protection and chloride ion resistance with environmental compliance.",
    targetIndustries: ["Construction Chemicals"],
    keywords: ["micro emulsion", "low voc", "silane siloxane", "penetrating sealer", "concrete protection", "waterborne sealer", "infrastructure protection", "bridge protection"],
    source: "text",
    pdfName: null,
  },

  // ── PAINTS & COATINGS ADDITIVES ──────────────────────────────────────────
  {
    name: "Rheology Modifiers (HEC / HEUR / HASE)",
    description: "Range of cellulosic (HEC) and synthetic associative thickeners (HEUR, HASE) for paints and coatings. Provide viscosity control, sag resistance, and application properties in waterborne systems.",
    applications: "Architectural paints, industrial coatings, adhesives, and construction chemicals requiring controlled rheology, anti-sedimentation, and brushing/rolling characteristics.",
    targetIndustries: ["Paints & Coatings", "Construction Chemicals", "Adhesives & Sealants"],
    keywords: ["rheology modifier", "hec", "heur", "hase", "thickener", "associative thickener", "viscosity", "cellulosic", "paint additive", "waterborne coating"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Dispersing & Wetting Agents (Paints)",
    description: "High-molecular-weight polyacrylate dispersants, block copolymers, and non-ionic surfactants for pigment and filler dispersion in paint and coating systems.",
    applications: "Dispersion of organic pigments, inorganic fillers, and carbon black in architectural paints, industrial coatings, and inks. Prevent flocculation and improve color strength.",
    targetIndustries: ["Paints & Coatings"],
    keywords: ["dispersant", "wetting agent", "polyacrylate", "pigment disperser", "block copolymer", "paint additive", "surfactant", "anti-flocculation", "color strength"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Defoamers & De-aerators (Paints & Coatings)",
    description: "Silicone oil-based, modified polysiloxane, and mineral oil with hydrophobic silica defoamers for waterborne and solventborne coating systems.",
    applications: "Foam and micro-bubble elimination during paint manufacture and application. Suitable for architectural, wood, and industrial coatings.",
    targetIndustries: ["Paints & Coatings", "Adhesives & Sealants"],
    keywords: ["defoamer", "de-aerator", "paint defoamer", "silicone defoamer", "coating additive", "foam control", "polysiloxane defoamer", "waterborne defoamer"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Matting Agents (Precipitated Silica / Wax)",
    description: "Precipitated synthetic silica, PE wax, and polyamide wax matting agents in untreated and wax-treated grades for controlled gloss reduction in coatings.",
    applications: "Matting of architectural paints, wood coatings, leather finishes, and industrial coatings to achieve satin, semi-gloss, or matte appearances.",
    targetIndustries: ["Paints & Coatings", "Leather"],
    keywords: ["matting agent", "precipitated silica", "pe wax", "polyamide wax", "gloss reduction", "matte finish", "coating matting", "wood coating", "satin"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Adhesion Promoters (Silanes & Resins)",
    description: "Organo-functional silanes, chlorinated polyolefins, and acrylic resins for adhesion promotion between coatings and difficult-to-bond substrates.",
    applications: "Promotion of adhesion to glass, metals, polyolefins, and mineral substrates in paints, adhesives, sealants, and composite materials.",
    targetIndustries: ["Paints & Coatings", "Adhesives & Sealants", "Construction Chemicals"],
    keywords: ["adhesion promoter", "silane", "chlorinated polyolefin", "acrylic resin", "bonding agent", "adhesion", "substrate bonding", "primer", "coupling agent"],
    source: "text",
    pdfName: null,
  },
  {
    name: "UV Absorbers & HALS Light Stabilizers",
    description: "Benzotriazole, triazine, and benzophenone UV absorbers combined with hindered amine light stabilizers (HALS) for protection of coatings and plastics from UV degradation.",
    applications: "UV protection for automotive clearcoats, architectural paints, wood finishes, and plastic masterbatches. Prevents yellowing, chalking, and gloss loss.",
    targetIndustries: ["Paints & Coatings", "PVC & Plastics", "Rubber & Latex"],
    keywords: ["uv absorber", "hals", "light stabilizer", "benzotriazole", "triazine", "benzophenone", "uv protection", "weathering", "photostabilizer", "anti-yellowing"],
    source: "text",
    pdfName: null,
  },

  // ── ORGANIC PIGMENTS ─────────────────────────────────────────────────────
  {
    name: "Phthalocyanine Pigments (Blues & Greens)",
    description: "Copper phthalocyanine (CuPc) pigments in blue and green shades. High-performance organic pigments with excellent lightfastness, heat stability, and chemical resistance.",
    applications: "Architectural paints, automotive coatings, printing inks, rubber compounding, and plastic masterbatches requiring brilliant, durable blue and green shades.",
    targetIndustries: ["Paints & Coatings", "Rubber & Latex", "PVC & Plastics"],
    keywords: ["phthalocyanine", "copper phthalocyanine", "cupc", "blue pigment", "green pigment", "organic pigment", "lightfast pigment", "masterbatch pigment", "printing ink"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Quinacridone Pigments (Reds, Violets & Magentas)",
    description: "Linear and unsubstituted quinacridone pigments in red, violet, and magenta shades. Outstanding lightfastness, transparency, and heat stability for demanding applications.",
    applications: "Automotive OEM and refinish paints, high-performance architectural coatings, printing inks, and plastic masterbatches requiring durable red and violet shades.",
    targetIndustries: ["Paints & Coatings", "PVC & Plastics"],
    keywords: ["quinacridone", "red pigment", "violet pigment", "magenta pigment", "organic pigment", "automotive pigment", "transparent pigment", "lightfast", "high performance pigment"],
    source: "text",
    pdfName: null,
  },
  {
    name: "DPP Pigments (Diketopyrrolopyrrole – Reds & Oranges)",
    description: "Diketopyrrolopyrrole (DPP) pigments in red and orange shades with the highest lightfastness rating (8/8). Superior weather resistance and brilliance.",
    applications: "Automotive coatings, high-durability architectural paints, and premium plastic applications where maximum lightfastness and outdoor durability are critical.",
    targetIndustries: ["Paints & Coatings", "PVC & Plastics"],
    keywords: ["dpp", "diketopyrrolopyrrole", "red pigment", "orange pigment", "lightfastness 8", "automotive pigment", "weather resistant pigment", "high durability", "organic pigment"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Azo Pigments (Yellows, Oranges & Reds)",
    description: "High-grade monoazo and disazo organic pigments in yellow, orange, and red shades. Good cost-performance ratio with adequate lightfastness for general-purpose applications.",
    applications: "General-purpose paints, printing inks, rubber compounding, and plastic masterbatches requiring bright yellow, orange, or red hues at competitive cost.",
    targetIndustries: ["Paints & Coatings", "Rubber & Latex", "PVC & Plastics"],
    keywords: ["azo pigment", "monoazo", "disazo", "yellow pigment", "orange pigment", "red pigment", "organic pigment", "printing ink pigment", "rubber pigment", "cost effective"],
    source: "text",
    pdfName: null,
  },

  // ── SILANES ──────────────────────────────────────────────────────────────
  {
    name: "Amino Silanes (APTES / APTMS / DAMO)",
    description: "3-Aminopropyltriethoxysilane (APTES, CAS 919-30-2), 3-Aminopropyltrimethoxysilane (APTMS, CAS 13822-56-5), and N-Aminoethyl-3-aminopropyltrimethoxysilane (DAMO, CAS 1760-24-3). Bifunctional coupling agents with reactive amino groups.",
    applications: "Adhesion promoters for urethane and epoxy systems, filler surface treatment for composites, epoxy curing agent (DAMO), and glass fiber sizing.",
    targetIndustries: ["Paints & Coatings", "Adhesives & Sealants", "Rubber & Latex", "Construction Chemicals"],
    keywords: ["amino silane", "aptes", "aptms", "damo", "aminopropyl", "coupling agent", "epoxy adhesion", "filler treatment", "glass fiber", "silane"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Epoxy Silanes (GLYMO / Cycloaliphatic Epoxy)",
    description: "3-Glycidoxypropyltrimethoxysilane (GLYMO, CAS 2530-83-8) and 2-(3,4-Epoxycyclohexyl)ethyltrimethoxysilane (CAS 3388-04-3). Epoxy-functional silane coupling agents.",
    applications: "Moisture resistance enhancement in adhesives, sealants, and composites. High-performance structural adhesives (cycloaliphatic grade). Glass fiber reinforced plastics.",
    targetIndustries: ["Adhesives & Sealants", "Paints & Coatings", "Construction Chemicals"],
    keywords: ["epoxy silane", "glymo", "glycidoxy", "coupling agent", "epoxy coupling", "moisture resistance", "adhesive silane", "composites", "structural adhesive"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Vinyl Silanes (VTES / VTMO)",
    description: "Vinyltriethoxysilane (VTES, CAS 78-08-0) and Vinyltrimethoxysilane (VTMO, CAS 2768-02-7). Vinyl-functional silane coupling agents for polymer crosslinking.",
    applications: "Moisture-cure crosslinking of polyethylene (XLPE) for cable insulation. Glass fiber sizing. Coupling agent in polyolefin composites.",
    targetIndustries: ["Wire & Cable", "PVC & Plastics"],
    keywords: ["vinyl silane", "vtes", "vtmo", "xlpe", "cable insulation", "polyethylene crosslinking", "moisture cure", "wire cable", "silane crosslinking", "polyolefin"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Methacrylate Silane (MEMO)",
    description: "3-Methacryloxypropyltrimethoxysilane (MEMO, CAS 2530-85-0). Methacrylate-functional silane coupling agent that bridges organic polymers and inorganic substrates.",
    applications: "Coupling agent in fiberglass-reinforced plastics, dental composites, and UV-curable coatings. Surface treatment for mineral fillers used in unsaturated polyester resins.",
    targetIndustries: ["Paints & Coatings", "Construction Chemicals", "Medical Devices"],
    keywords: ["memo", "methacrylate silane", "methacryloxysilane", "fiberglass", "frp", "uv coating", "dental composite", "mineral filler", "coupling agent", "silane"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Alkyl Silanes (Isobutyl / Propyl / Octyl)",
    description: "Hydrophobic alkylsilanes including Isobutyltrimethoxysilane (IBTMO, CAS 18395-30-7), Propyltrimethoxysilane (PTMO, CAS 1067-25-0), and Octyltriethoxysilane for surface hydrophobicity.",
    applications: "Stone and concrete water repellency. Hydrophobic surface treatment for mineral substrates, masonry, and building materials.",
    targetIndustries: ["Construction Chemicals", "Paints & Coatings"],
    keywords: ["alkyl silane", "isobutyl silane", "propyl silane", "octyl silane", "ibtmo", "hydrophobic treatment", "stone water repellent", "masonry waterproofing", "silane sealer"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Sealant Silanes (MTAS / Ketoxime)",
    description: "Methyltriacetoxysilane (MTAS, CAS 4253-34-3) and Methyltris(methylethylketoxime)silane (CAS 22984-54-9). Crosslinker silanes for RTV silicone sealants.",
    applications: "Acetoxy-cure (MTAS) and oxime-cure RTV silicone sealants for construction, glazing, and automotive assembly.",
    targetIndustries: ["Adhesives & Sealants", "Construction Chemicals"],
    keywords: ["sealant silane", "mtas", "ketoxime silane", "rtv sealant", "silicone sealant", "acetoxy cure", "oxime cure", "crosslinker", "glazing sealant"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Cyclic Siloxane D4 (Octamethylcyclotetrasiloxane)",
    description: "Octamethylcyclotetrasiloxane (D4, CAS 556-67-2). Cyclic siloxane used as an intermediate in PDMS synthesis and as a processing solvent in personal care.",
    applications: "PDMS and silicone polymer intermediate. Silicone fluid manufacturing. Volatile carrier in cosmetic and personal care formulations.",
    targetIndustries: ["Personal Care & Cosmetics", "Pharmaceuticals"],
    keywords: ["d4", "cyclic siloxane", "octamethylcyclotetrasiloxane", "pdms intermediate", "silicone intermediate", "volatile silicone", "cosmetic silicone"],
    source: "text",
    pdfName: null,
  },
  {
    name: "HMDS (Hexamethyldisilazane)",
    description: "Hexamethyldisilazane (HMDS, CAS 999-97-3). A silazane compound used as a surface passivating and adhesion-promoting agent in semiconductor manufacturing.",
    applications: "Semiconductor photolithography: promotes photoresist adhesion to silicon wafers. Also used for surface silylation of chromatography materials and desiccation of laboratory glassware.",
    targetIndustries: ["Medical Devices"],
    keywords: ["hmds", "hexamethyldisilazane", "semiconductor", "photolithography", "photoresist adhesion", "silicon wafer", "surface silylation", "chromatography", "silazane"],
    source: "text",
    pdfName: null,
  },

  // ── FLAME RETARDANTS ─────────────────────────────────────────────────────
  {
    name: "TCPP Flame Retardant (Tris-Chloroisopropyl Phosphate)",
    description: "Tris(2-chloroisopropyl) phosphate (TCPP) is a chlorinated organophosphate flame retardant and plasticizer for polyurethane foams.",
    applications: "Flame retardant for rigid and flexible polyurethane (PU) foams used in furniture, insulation panels, mattresses, and automotive seating.",
    targetIndustries: ["PVC & Plastics", "Construction Chemicals"],
    keywords: ["tcpp", "flame retardant", "chlorinated phosphate", "pu foam", "polyurethane", "furniture foam", "insulation", "fire retardant", "organophosphate"],
    source: "text",
    pdfName: null,
  },
  {
    name: "TEP (Triethyl Phosphate) Flame Retardant",
    description: "Triethyl Phosphate (TEP), a non-halogenated organophosphate flame retardant and plasticizer for unsaturated polyester (UPE) resins and polyurethanes.",
    applications: "Flame retardant and plasticizer for UPE resins (FRP composites, laminates) and flexible polyurethane. Also used as a solvent and processing aid.",
    targetIndustries: ["PVC & Plastics", "Adhesives & Sealants"],
    keywords: ["tep", "triethyl phosphate", "flame retardant", "upe resin", "frp", "plasticizer", "non halogen", "polyurethane", "organophosphate", "fire retardant"],
    source: "text",
    pdfName: null,
  },
  {
    name: "BDP Halogen-Free Flame Retardant",
    description: "Bisphenol-A bis(diphenyl phosphate) (BDP), a halogen-free reactive organophosphate flame retardant for engineering plastics.",
    applications: "Halogen-free flame retardant for PC/ABS blends, engineering thermoplastics, and electronic components requiring RoHS/REACH compliance.",
    targetIndustries: ["PVC & Plastics", "Wire & Cable"],
    keywords: ["bdp", "halogen free", "flame retardant", "bisphenol phosphate", "engineering plastic", "pc abs", "rohs", "reach", "reactive flame retardant", "non halogen"],
    source: "text",
    pdfName: null,
  },
  {
    name: "IPPP Flame Retardant (PVC & Rubber)",
    description: "Isopropylated Phenyl Phosphate (IPPP), an organophosphate flame retardant and plasticizer primarily for PVC and synthetic rubber applications.",
    applications: "Flame retardant plasticizer for flexible PVC cables, synthetic rubber goods, and foam products. Provides both flame retardancy and flexibility improvement.",
    targetIndustries: ["PVC & Plastics", "Rubber & Latex", "Wire & Cable"],
    keywords: ["ippp", "isopropylated phenyl phosphate", "pvc flame retardant", "rubber flame retardant", "plasticizer", "flexible pvc", "cable compound", "organophosphate"],
    source: "text",
    pdfName: null,
  },

  // ── OTHER ─────────────────────────────────────────────────────────────────
  {
    name: "N220 Carbon Black",
    description: "N220 carbon black is a high surface area, medium structure carbon black from the KOHLENSTOFF range. Provides good extrudability in compounds along with high tensile strength and wear resistance.",
    applications: "Used in tire tread compounds for passenger and truck tires, conveyor belts, and rubber compounds requiring superior wear and tear resistance.",
    targetIndustries: ["Rubber & Latex", "Footwear", "Wire & Cable", "PVC & Plastics"],
    keywords: ["carbon black", "n220", "rubber filler", "tire compound", "conveyor belt", "wear resistance", "tensile strength", "kohlenstoff", "rubber reinforcement", "carbon"],
    source: "pdf",
    pdfName: "TDS_N220_v2.0.pdf",
  },
  {
    name: "Fumed Silica",
    description: "Fumed silica (pyrogenic silica) is an ultrafine, high-purity amorphous silicon dioxide produced by flame hydrolysis. It has extremely high surface area, low bulk density, and unique thixotropic properties.",
    applications: "Thickening and anti-settling agent in paints, coatings, and adhesives. Reinforcing filler in silicone rubber, flow aid in powders, and anti-caking agent in various industrial applications.",
    targetIndustries: ["Paints & Coatings", "Adhesives & Sealants", "Rubber & Latex", "Pharmaceuticals", "Personal Care & Cosmetics", "Construction Chemicals"],
    keywords: ["fumed silica", "pyrogenic silica", "silicon dioxide", "sio2", "thickener", "rheology modifier", "anti-settling", "reinforcing filler", "aerosil", "thixotropic"],
    source: "text",
    pdfName: null,
  },
];
