import type { InsertProduct } from "@shared/schema";

export const seedProducts: InsertProduct[] = [
  {
    name: "N220 Carbon Black",
    description: "N220 carbon black is a high surface area, medium structure carbon black from the KOHLENSTOFF range. It provides good extrudability in compounds along with high tensile strength and wear resistance.",
    applications: "Used in tire tread compounds for passenger and truck tires, conveyor belts, and rubber compounds requiring superior wear and tear resistance.",
    targetIndustries: ["Rubber & Latex", "Footwear", "Wire & Cable", "PVC & Plastics"],
    keywords: ["carbon black", "n220", "rubber filler", "tire compound", "conveyor belt", "wear resistance", "tensile strength", "kohlenstoff", "rubber reinforcement", "carbon"],
    source: "pdf",
    pdfName: "TDS_N220_v2.0.pdf",
  },
  {
    name: "Aquaphobe WR 22",
    description: "AQUAPHOBE WR 22 is a water-thinnable, solvent-free silane-siloxane emulsion from Resil Chemicals with excellent penetration properties. It provides superior water repellency for mineral substrates and is eco-friendly.",
    applications: "Used for hydrophobic impregnation and priming of construction materials including bricks, sandstone, fiber cement boards, aerated concrete, and mineral plasters. Serves as a water-repellent primer for emulsion paints.",
    targetIndustries: ["Construction Chemicals", "Paints & Coatings"],
    keywords: ["water repellent", "aquaphobe", "silane siloxane", "hydrophobic", "impregnation", "waterproofing", "construction", "primer", "resil", "wr 22"],
    source: "pdf",
    pdfName: "AQUAPHOBE_WR_22_TDS.pdf",
  },
  {
    name: "Resilwet 103",
    description: "RESILWET 103 is a polyether modified trisiloxane adjuvant (3-(Polyoxyethylene)propylheptamethyltrisiloxane) from Resil Chemicals. It is a highly effective non-ionic surfactant used as a spray adjuvant.",
    applications: "Used as a spray adjuvant in agricultural applications for improved wetting, spreading and penetration of agrochemical formulations on plant surfaces.",
    targetIndustries: ["Agriculture & Agrochemicals"],
    keywords: ["spray adjuvant", "resilwet", "trisiloxane", "surfactant", "wetter", "spreader", "agricultural adjuvant", "agrochemical", "resil", "silicone surfactant"],
    source: "pdf",
    pdfName: "RESILWET_103_SDS.pdf",
  },
  {
    name: "Resifluid-350 Silicone Fluid",
    description: "RESIFLUID-350 is a colorless polydimethylsiloxane (PDMS) fluid from Resil Chemicals with approximately 370 cst viscosity. It offers excellent thermal stability, low surface tension, high compressibility, and good dielectric properties.",
    applications: "Used as a release agent, antifoam, hydraulic fluid, surface-active material, lubricant, and as an additive in polishes and chemical specialties.",
    targetIndustries: ["Rubber & Latex", "Personal Care & Cosmetics", "Pharmaceuticals", "Paper & Pulp", "Food Processing", "Medical Devices"],
    keywords: ["silicone fluid", "resifluid", "pdms", "polydimethylsiloxane", "release agent", "antifoam", "lubricant", "silicone oil", "350 cst", "resil"],
    source: "pdf",
    pdfName: "TDS-RESILFLUID-350.pdf",
  },
  {
    name: "DMC Silicone Fluids (Dimethicone)",
    description: "DMC grade silicone fluids are clear, colorless polydimethylsiloxane fluids from Resil Chemicals available in viscosities from 0.65 to 60,000 cst. They are non-greasy, form protective breathable films, and have excellent water repellency.",
    applications: "Used for siliconization of glass, metals, plastics, and rubber. Key applications include pharmaceutical and cosmetic formulations (skin care, sun care, oral care), medical device lubrication (syringes, needles), and industrial lubrication.",
    targetIndustries: ["Personal Care & Cosmetics", "Pharmaceuticals", "Medical Devices", "Rubber & Latex", "PVC & Plastics"],
    keywords: ["dimethicone", "dmc", "silicone fluid", "pdms", "polydimethylsiloxane", "cosmetic grade", "pharmaceutical grade", "siliconization", "lubricant", "resil"],
    source: "pdf",
    pdfName: "DMC_FLUIDS_TDS.pdf",
  },
  {
    name: "Fumed Silica",
    description: "Fumed silica (pyrogenic silica) is an ultrafine, high-purity amorphous silicon dioxide produced by flame hydrolysis. It has extremely high surface area, low bulk density, and unique thixotropic properties.",
    applications: "Used as a thickening and anti-settling agent in paints, coatings, and adhesives. Also used as a reinforcing filler in silicone rubber, flow aid in powders, and anti-caking agent in various industrial applications.",
    targetIndustries: ["Paints & Coatings", "Adhesives & Sealants", "Rubber & Latex", "Pharmaceuticals", "Personal Care & Cosmetics", "Construction Chemicals"],
    keywords: ["fumed silica", "pyrogenic silica", "silicon dioxide", "sio2", "thickener", "rheology modifier", "anti-settling", "reinforcing filler", "aerosil", "thixotropic"],
    source: "text",
    pdfName: null,
  },
  {
    name: "Silicone Oil",
    description: "Silicone oil (polydimethylsiloxane/PDMS) is a versatile clear synthetic fluid available in various viscosity grades. It offers excellent thermal stability, chemical inertness, low surface tension, and superior water repellency.",
    applications: "Used as a mold release agent in rubber and plastics, as a lubricant in medical devices and industrial equipment, as a base fluid in personal care products, and as a heat transfer medium in various processes.",
    targetIndustries: ["Rubber & Latex", "Medical Devices", "Personal Care & Cosmetics", "Pharmaceuticals", "PVC & Plastics", "Food Processing", "Paper & Pulp"],
    keywords: ["silicone oil", "pdms", "polydimethylsiloxane", "silicone fluid", "release agent", "mold release", "lubricant", "heat transfer", "dielectric fluid", "silicone"],
    source: "text",
    pdfName: null,
  },
];
